# ==================== TEST PROFILE ====================

# Testcontainers vai sobrescrever essas configurações automaticamente
spring.datasource.url=jdbc:postgresql://localhost:5433/deliverydb_test
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Logging
logging.level.root=WARN
logging.level.com.pedroferreira.deliveryapplication=DEBUG
logging.level.org.testcontainers=INFO

# Desabilitar Swagger em testes
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

# Desabilitar Security em testes (se necessário)
# spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfigurationz